export interface WordWithHint {
  word: string;
  hint: string;
}

export const wordsWithHints: WordWithHint[] = [
  // Mat & Dryck
  { word: "Glass", hint: "En söt fryst efterrätt" },
  { word: "Godis", hint: "Sött man kan äta efter maten" },
  { word: "Sallad", hint: "Grönsaker på en tallrik" },
  { word: "Gurka", hint: "Grön och krispig, ofta i sallad" },
  { word: "Tomat", hint: "Röd frukt som används i sallad och sås" },
  { word: "Paprika", hint: "Kan vara röd, gul eller grön, används i matlagning" },
  { word: "Grädde", hint: "Tjock mjölkprodukt som kan vispas" },
  { word: "Ost", hint: "Tillverkas av mjölk och finns i många sorter" },
  { word: "Ris", hint: "Små vita korn som kokas som tillbehör" },
  { word: "Pasta", hint: "Italiensk mat som spaghetti och penne" },
  { word: "Kyckling", hint: "Fågel som ofta äts som kött" },
  { word: "Mjölk", hint: "Vit dryck från kor" },
  { word: "Fil", hint: "Surt mjölkprodukt, populär till frukost" },
  { word: "Yogurth", hint: "Mjölkprodukt som ofta äts med frukt" },
  { word: "Kräm", hint: "Söt eller fyllig dessert" },
  { word: "Mousse", hint: "Luftig dessert, ofta choklad eller bär" },
  { word: "Choklad", hint: "Sött brunt godis gjort på kakao" },
  { word: "Lakrits", hint: "Svart godis med speciell smak" },
  { word: "Äpple", hint: "Rund frukt, röd, grön eller gul" },
  { word: "Päron", hint: "Söt frukt med smal topp och bred botten" },
  { word: "Passionsfrukt", hint: "Gul-orange frukt med små svarta kärnor" },
  { word: "Apelsin", hint: "Citrusfrukt som är orange" },
  { word: "Druvor", hint: "Små frukter, gröna eller lila, på klasar" },

  //Musik
  {word: "Melodi", hint: "En följd av toner som bilder en igenkännbar musikalisk linje."},
  {word: "Harmoni", hint: "Bär flera toner klingar samtidigt på ett behagligt sätt."},
  {word: "Rytm", hint: "Mönstret av betoningar och tidsvärden i musik. BPM (Beats Per Minute)"},
  {word: "Genre", hint: "en kategori av musik, som exempelvis rock, jazz eller klassiskt."},
  {word: "Ackord", hint: "Tre eller fler toner som spelas samtidigt."},
  {word: "Noter", hint: "Symboler som används för att skriva ner och tolka musik."},


  // Djur
  { word: "Gris", hint: "Rosa djur som ofta bor på bondgård" },
  { word: "Ko", hint: "Ger mjölk på bondgården" },
  { word: "Tjur", hint: "Han-ko med horn" },
  { word: "Höna", hint: "Lägger ägg" },
  { word: "Tupp", hint: "Han-höna, gal på morgonen" },
  { word: "Kalv", hint: "Ung ko" },
  { word: "Får", hint: "Djur som ger ull" },
  { word: "Bagge", hint: "Han-får" },
  { word: "Get", hint: "Djur som kan klättra på berg" },
  { word: "Åsna", hint: "Står ofta för last och gnäggar" },
  { word: "Häst", hint: "Rid- och travdjur" },
  { word: "Katt", hint: "Mjauar och spinner" },
  { word: "Hund", hint: "Voffar och vaktar" },
  { word: "Fågel", hint: "Har vingar och kan flyga" },
  { word: "Papegoja", hint: "Färgglad fågel som kan prata" },
  { word: "Skata", hint: "Svart-vit fågel, samlar på glänsande saker" },
  { word: "Duva", hint: "Fredens fågel" },
  { word: "Apa", hint: "Klättrar i träd och är smart" },
  { word: "Zebra", hint: "Svart-vit randig hästliknande djur" },
  { word: "Giraff", hint: "Högt djur med lång hals" },
  { word: "Noshörning", hint: "Stort djur med horn på nosen" },
  { word: "Krokodil", hint: "Stort reptildjur med vassa tänder" },
  { word: "Albatross", hint: "Stor havsfågel med lång vingspann" },
  { word: "Räv", hint: "Rött djur som är listigt" },
  { word: "Varg", hint: "Lever i flock och ylar" },
  { word: "Lo", hint: "Stor katt med tofsar på öronen" },
  { word: "Flodhäst", hint: "Stort djur som gillar vatten" },
  { word: "Pingvin", hint: "Fåglar som inte kan flyga men simmar" },
  { word: "Lejon", hint: "Kattdjur, kungen av djungeln" },
  { word: "Tiger", hint: "Randig katt från Asien" },
  { word: "Panter", hint: "Svart katt" },
  { word: "Puma", hint: "Stor katt som lever i Amerika" },

  // Sport & Spel
  { word: "Fotboll", hint: "Spelas med boll på en plan" },
  { word: "Ishockey", hint: "Spelas med puck på is" },
  { word: "Puck", hint: "Små skivor som används i hockey" },
  { word: "Spel", hint: "Något man tävlar i eller leker med" },
  { word: "Spelare", hint: "Person som deltar i ett spel" },
  { word: "Boll", hint: "Rund sak man kastar eller sparkar" },
  { word: "Kortlek", hint: "Kort som används i spel" },
  { word: "Spade", hint: "Ett kort i kortleken" },
  { word: "Hjärter", hint: "Rött kort med hjärtsymbol" },
  { word: "Ruter", hint: "Rött kort med diamant-symbol" },
  { word: "Klöver", hint: "Grönt kort med klöversymbol" },
  { word: "Ess", hint: "Det högsta kortet i en svit" },
  { word: "Kung", hint: "Kort med kung på" },
  { word: "Dam", hint: "Kort med dam på" },
  { word: "Knekt", hint: "Kort med knekt på" },
  { word: "Joker", hint: "Specialkort i kortspel" },

  // Fordon & Maskiner
  { word: "Cykel", hint: "Tvåhjuligt transportmedel" },
  { word: "Flygplan", hint: "Fordon som flyger" },
  { word: "Ballong", hint: "Kan flyga och fyllas med luft" },
  { word: "Robot", hint: "Maskin som kan utföra uppgifter" },
  { word: "Kanon", hint: "Stort eldvapen" },
  { word: "Pistol", hint: "Litet eldvapen" },
  { word: "Gevär", hint: "Långt eldvapen" },
  { word: "Tank", hint: "Stridsfordon med pansar" },
  { word: "Soldat", hint: "Person som tjänstgör i armén" },
  { word: "Armé", hint: "Stort militärt förband" },
  { word: "Militär", hint: "Person som jobbar inom försvar" },
  { word: "Bil", hint: "Fyrhjuligt transportmedel" },
  { word: "Lastbil", hint: "Stort fordon som fraktar gods" },
  { word: "Motorcykel", hint: "Tvåhjuligt fordon med motor" },
  { word: "Båt", hint: "Fordon som flyter på vatten" },
  { word: "Skoter", hint: "Fordon som körs på snö" },
  { word: "Tåg", hint: "Transport på räls" },
  { word: "Raket", hint: "Flyger ut i rymden" },
  { word: "Helikopter", hint: "Flygande fordon med rotorblad" },
  { word: "Traktor", hint: "Jordbruksmaskin" },

  // Kropp & Familj
  { word: "Mamma", hint: "Din mamma" },
  { word: "Pappa", hint: "Din pappa" },
  { word: "Bror", hint: "Din manliga syskon" },
  { word: "Syster", hint: "Din kvinnliga syskon" },
  { word: "Farfar", hint: "Din pappas pappa" },
  { word: "Farmor", hint: "Din pappas mamma" },
  { word: "Morfar", hint: "Din mammas pappa" },
  { word: "Mormor", hint: "Din mammas mamma" },
  { word: "Son", hint: "Ditt manliga barn" },
  { word: "Dotter", hint: "Ditt kvinnliga barn" },
  { word: "Kusin", hint: "Barn till din moster/faster eller morbror/farbror" },
  { word: "Moster", hint: "Din mammas syster" },
  { word: "Faster", hint: "Din pappas syster" },
  { word: "Farbror", hint: "Din pappas bror" },
  { word: "Morbror", hint: "Din mammas bror" },
  { word: "Sambo", hint: "Person du bor med" },
  { word: "Make", hint: "Din man" },
  { word: "Maka", hint: "Din hustru" },
  { word: "Partner", hint: "Person du delar livet med" },
  { word: "Vän", hint: "Nära kompis" },
  { word: "Kompis", hint: "Person du umgås med" },
  { word: "Granne", hint: "Person som bor nära dig" },

  // Natur & Väder
  { word: "Berg", hint: "Höjd i naturen" },
  { word: "Kulle", hint: "Liten höjd i naturen" },
  { word: "Slättland", hint: "Platt landskap" },
  { word: "Skogen", hint: "Område med många träd" },
  { word: "Julgran", hint: "Gran som pyntas vid jul" },
  { word: "Regn", hint: "Vatten som faller från himlen" },
  { word: "Snö", hint: "Vitt från himlen på vintern" },
  { word: "Hagel", hint: "Små iskorn som faller från himlen" },
  { word: "Dimma", hint: "Tjock luft som gör det svårt att se" },
  { word: "Dis", hint: "Lätt dimma" },
  { word: "Solsken", hint: "När solen skiner" },
  { word: "Solstråle", hint: "En stråle från solen" },
  { word: "Måne", hint: "Lyser på natten" },
  { word: "Vulkan", hint: "Berg som kan spruta lava" },
  { word: "Jordbävning", hint: "Marken skakar" },
  { word: "Tsunami", hint: "Stor havsvåg" },
  { word: "Orkan", hint: "Mycket stark vind" },
  { word: "Tornado", hint: "Virvelvind på land" },
  { word: "Cyklon", hint: "Virvelstorm" },
  { word: "Monsun", hint: "Regnperiod i vissa länder" },

  // Kändisar
  { word: "Zlatan Ibrahimovich", hint: "Svensk fotbollsspelare" },
  { word: "David Beckham", hint: "Engelsk fotbollsspelare" },
  { word: "David Schwimmer", hint: "Skådespelare i Friends" },
  { word: "Lisa Kudrow", hint: "Skådespelare i Friends" },
  { word: "Matt Leblanc", hint: "Skådespelare i Friends" },
  { word: "Courteney Cox", hint: "Skådespelare i Friends" },
  { word: "Jennifer Aniston", hint: "Skådespelare i Friends" },
  { word: "Matthew Perry", hint: "Skådespelare i Friends" },
  { word: "Taylor Swift", hint: "Amerikansk popsångerska" },
  { word: "Katy Perry", hint: "Amerikansk popsångerska" },
  { word: "Ariana Grande", hint: "Popstjärna med höga toner" },
  { word: "Rihanna", hint: "Sångerska från Barbados" },
  { word: "Beyoncé", hint: "Sångerska och skådespelerska" },
  { word: "Shakira", hint: "Kolombiansk popsångerska" },
  { word: "Cristiano Ronaldo", hint: "Portugisisk fotbollsstjärna" },
  { word: "Lionel Messi", hint: "Argentinsk fotbollsstjärna" },
  { word: "Roger Federer", hint: "Schweizisk tennisspelare" },
  { word: "Serena Williams", hint: "Amerikansk tennisspelare" },
  { word: "LeBron James", hint: "Basketspelare i NBA" },
  { word: "Michael Jordan", hint: "Legend inom basket" },
  { word: "Usain Bolt", hint: "Världens snabbaste man" },
  { word: "Gal Gadot", hint: "Skådespelerska, Wonder Woman" },
  { word: "Scarlett Johansson", hint: "Skådespelerska, Black Widow" },
  { word: "Chris Hemsworth", hint: "Skådespelare, Thor" },
  { word: "Robert Downey Jr.", hint: "Skådespelare, Iron Man" },
  { word: "Emma Watson", hint: "Skådespelare, Hermione" },
  { word: "Daniel Radcliffe", hint: "Skådespelare, Harry Potter" },
  { word: "Rupert Grint", hint: "Skådespelare, Ron Weasley" },
  { word: "Tom Holland", hint: "Skådespelare, Spider-Man" },
  { word: "Zendaya", hint: "Skådespelare, Euphoria" },
  { word: "Dwayne Johnson", hint: "Skådespelare och wrestlare" },
  { word: "Lady Gaga", hint: "Sångerska med unika outfits" },

  // Färg & Former
  { word: "Röd", hint: "Färg som symboliserar kärlek" },
  { word: "Blå", hint: "Färg som himlen ofta har" },
  { word: "Grön", hint: "Färg som gräs" },
  { word: "Gul", hint: "Färg som solen" },
  { word: "Svart", hint: "Färg som natt" },
  { word: "Vit", hint: "Färg som snö" },
  { word: "Lila", hint: "Färg mellan blå och röd" },
  { word: "Orange", hint: "Färg som apelsin" },
  { word: "Rosa", hint: "Färg som ofta associeras med romantik" },
  { word: "Brun", hint: "Färg som jord" },
  { word: "Grå", hint: "Färg mellan svart och vit" },
  { word: "Turkos", hint: "Blå-grön färg" },
  { word: "Indigo", hint: "Mörkblå färg" },
  { word: "Magenta", hint: "Röd-lila färg" },
  { word: "Cyan", hint: "Ljusblå färg" },
  { word: "Lime", hint: "Grön färg som citrusfrukten" },
  { word: "Violett", hint: "Lila färg" },
  { word: "Beige", hint: "Ljusbrun färg" },
  { word: "Marinblå", hint: "Mörkblå färg" },
  { word: "Smaragdgrön", hint: "Grön färg som ädelstenen" },
  { word: "Silver", hint: "Metallfärg" },
  { word: "Guld", hint: "Metallfärg" },
  { word: "Brons", hint: "Metallfärg" },
  
  // Former
  { word: "Triangel", hint: "Figur med tre hörn" },
  { word: "Fyrkant", hint: "Figur med fyra lika sidor" },
  { word: "Cirkel", hint: "Rund figur" },
  { word: "Rektangel", hint: "Figur med fyra sidor, två långa och två korta" },
  { word: "Oval", hint: "Avlång cirkelform" },
  { word: "Pentagon", hint: "Figur med fem sidor" },
  { word: "Hexagon", hint: "Figur med sex sidor" },
  { word: "Heptagon", hint: "Figur med sju sidor" },
  { word: "Octagon", hint: "Figur med åtta sidor" },
  { word: "Stjärna", hint: "Figur med spetsar" },
  { word: "Hjärta", hint: "Kärleks-symbol" },
  { word: "Diamant", hint: "Form som ett lutande kvadrat" },
  { word: "Pil", hint: "Figur som pekar åt ett håll" },
  { word: "Kors", hint: "Två linjer som korsar varandra" },
  { word: "Måne", hint: "Halvmåne eller cirkelformad himlakropp" },
  { word: "Sol", hint: "Rund himlakropp som ger ljus" },
  { word: "Crescent", hint: "Halvmåneform" },
  { word: "Spiral", hint: "Snurrande kurva" },
  { word: "Ellips", hint: "Avlång cirkelform" },
  { word: "Trapets", hint: "Fyra sidor, två parallella" },
  { word: "Parallellogram", hint: "Fyra sidor med parallella sidor" },
  { word: "Kub", hint: "Tredimensionell figur med sex kvadrater" },
  { word: "Klot", hint: "Rund tredimensionell figur" },
  { word: "Cylinder", hint: "Tredimensionell figur med cirkulär bas" },
  { word: "Kon", hint: "Tredimensionell figur med cirkulär bas och spets" },
  { word: "Pyramid", hint: "Tredimensionell figur med trianglar som sidor" },
  { word: "Tetrahedron", hint: "Pyramid med fyra triangelsidor" },
  { word: "Dodekahedron", hint: "Tredimensionell figur med tolv sidor" },
  { word: "Ikosahedron", hint: "Tredimensionell figur med tjugo sidor" },

  // Fantasy & Sagoväsen
  { word: "Vampyr", hint: "Dricker blod på natten" },
  { word: "Spöke", hint: "Osynlig eller genomskinlig varelse" },
  { word: "Varulv", hint: "Förvandlas till en stor vargliknande varelse" },
  { word: "Monster", hint: "Skrämmande varelse" },
  { word: "Hjälte", hint: "Räddar människor" },
  { word: "Drake", hint: "Eldandande reptil" },
  { word: "Riddare", hint: "Kämpar i rustning" },
  { word: "Viking", hint: "Historisk nordisk krigare" },
  { word: "Barbar", hint: "Vild krigare" },
  { word: "Troll", hint: "Stort och konstigt väsen" },
  { word: "Fe", hint: "Magisk liten varelse" },
  { word: "Alv", hint: "Långörad, magisk varelse" },
  { word: "Ork", hint: "Stark och grön varelse" },
  { word: "Jätte", hint: "Stor varelse" },
  { word: "Ogre", hint: "Stor och stark varelse" },
  { word: "Demon", hint: "Ond andevarelse" },
  { word: "Älva", hint: "Liten magisk varelse" },
  { word: "Tomte", hint: "Liten figur som bor på gårdar" },
  { word: "Häxa", hint: "Person med magi" },
  { word: "Trollkarl", hint: "Magiker" },
  { word: "Magiker", hint: "Utför magi" },
  { word: "Nymf", hint: "Naturens ande" },
  { word: "Kentaur", hint: "Halv människa, halv häst" },
  { word: "Minotaur", hint: "Halv människa, halvt tjur" },
  { word: "Sjöjungfru", hint: "Överdel människa, underdel fisk" },
  { word: "Havsrå", hint: "Farlig havsvarelse i sagor" },
  { word: "Griffin", hint: "Lejon kropp, örn huvud" },
  { word: "Fenrisulv", hint: "Mytologisk gigantisk varg" },
  { word: "Skelett", hint: "Ben från död varelse" },
  { word: "Zombielik", hint: "Odöd som går runt" },
  { word: "Golem", hint: "Lerfigur som blir levande" },
  { word: "Djinn", hint: "Magisk ande" },
  { word: "Pegasus", hint: "Vingad häst" },
  { word: "Hippogriff", hint: "Häst med örnvingar" },
  { word: "Berserk", hint: "Vild krigare" },
  { word: "Sirén", hint: "Farlig havsvarelse som lockar sjömän" },
  { word: "Hydra", hint: "Flera huvud, mytologisk orm" },
  { word: "Chimär", hint: "Kombination av flera djur" },
  { word: "Trollkatt", hint: "Magisk katt" },
  { word: "Skogsvarelse", hint: "Bor i skogen" },
  { word: "Frostjätte", hint: "Jätte från is och snö" },
  { word: "Vildmarksvarelse", hint: "Bor i vildmarken" },
  { word: "Fenix", hint: "Brinner upp och återföds" },
  { word: "Dvärg", hint: "Kort människa, ofta stark" },
  { word: "Gnoll", hint: "Farlig sagovarelse" },
  { word: "Svartalf", hint: "Mörk alv" },
  { word: "Skogstroll", hint: "Bor i skogen" },
  { word: "Bergtroll", hint: "Bor i bergen" },
  { word: "Kobold", hint: "Liten mytologisk varelse" },
  { word: "Imp", hint: "Liten busig demon" },
  { word: "Garnorm", hint: "Orm i sagor som vaktar" },
  { word: "Stormdrake", hint: "Drake med stormkrafter" },
  { word: "Fantasifigur", hint: "Påhittad karaktär" },
  { word: "Hjältinna", hint: "Kvinnlig hjälte" },
  { word: "Krigshjälte", hint: "Hjälte i strid" },
  

];
